pipeline {

    agent any

    parameters {
        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')
       
    }

  
    stages {

        stage('Checkout') {
            steps {
                dir('terraform/Ci-CD/Ci-CD') {
                    git branch: 'main', url: 'https://github.com/Urmilaa/Terraform-examples.git'
                }
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'   
                ]]) {
                    dir('terraform/Ci-CD/Ci-CD') {
                        sh 'aws sts get-caller-identity'
                        sh 'terraform init'
                    }
                }
            }
        }
          stage('Terraform Validate') {
            steps {
                dir('terraform/Ci-CD/Ci-CD') {
                sh 'terraform validate'
                }
            }
        }
        stage('Terraform Plan') {
            steps {                                
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    dir('terraform/Ci-CD/Ci-CD') {
                        sh 'terraform plan -out=tfplan'
                        sh 'terraform show -no-color tfplan > tfplan.txt'
                    }
                }
            }
        }

        stage('Approval') {

            when {
                not { equals expected: true, actual: params.autoApprove }
            }

            steps {
                script {
                    def plan = readFile 'terraform/Ci-CD/Ci-CD/tfplan.txt'

                    input message: "Do you want to apply the plan?",
                    parameters: [
                        text(name: 'Terraform Plan', defaultValue: plan, description: 'Review Terraform Plan')
                    ]
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                 withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    dir('terraform/Ci-CD/Ci-CD') {
                        sh 'terraform apply -input=false tfplan'
                    }
                }
            }
        }
    }   

}
